version: '2'
services:
  postgres:
    image: debezium/example-postgres:1.9
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  zookeeper:
    hostname: zookeeper
    container_name: zookeeper
    image: 'bitnami/zookeeper:latest'
    ports:
      - "2181:2181"
    environment:
       - ALLOW_ANONYMOUS_LOGIN=yes    
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    restart: always    
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: ${IP}
      KAFKA_BROKER_ID: 1
      KAFKA_CREATE_TOPICS: "kafka-nifi-src:1:1,kafka-nifi-dst:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  
  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    environment:
      KAFKA_BROKERCONNECT: "kafka:9092"
      JVM_OPTS: "-Xms16M -Xmx512M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    ports:
      - 9000:9000
    depends_on:
      - kafka
  kconnect:
    image: debezium/connect:1.9
    ports:
      - 8083:8083
    environment:
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      STATUS_STORAGE_TOPIC: my_connect_statuses
      BOOTSTRAP_SERVERS: "kafka:9092"
    links:
      - zookeeper
      - postgres
    depends_on:
      - kafka
      - zookeeper
      - postgres 
  nifi:
    image: apache/nifi:latest
    ports:
      - "8080:8080" 
    environment:
       NIFI_WEB_HTTP_PORT: 8080
       NIFI_CLUSTER_IS_NODE: 'true'
       NIFI_CLUSTER_NODE_PROTOCOL_PORT: 8082
       NIFI_ZK_CONNECT_STRING: "zookeeper:2181"
       NIFI_ELECTION_MAX_WAIT: "1 min"
       NIFI_ZK_ROOT_NODE: "/nifi"
       NIFI_SENSITIVE_PROPS_KEY: "Ggokceggokcec"
  producer:
    build: ./producer
    environment:
      API_COVID: "https://api.covid19api.com/summary"
      TOPIC: kafka-nifi-src
      BOOTSTRAP_SERVER: "kafka:9092"
  consumer:
    build: ./consumer
    environment:
      TOPIC: kafka-nifi-dst
      BOOTSTRAP_SERVER: "kafka:9092"